### ISSUE TITLE
How do I configure the "Server side configuration"

### ISSUE THREAD

**Issue by petterssonm** [Azure-Samples/LiveMaps#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Create a local.settings.json in the "livemaps-api" function app and try to implement the array specified in "Server side configuration" (in the README file) https://github.com/Azure-Samples/LiveMaps#server-side-configuration  How should this be done correctly?

### Any log messages given by the failure
None
### Expected/desired behavior
Be able to launch the function app so that I can run the sample web app and get data into the application
### OS and Version?
Windows 10, Visual Studio 2019

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by maxmushkin** [comment]
Hi Mattias,

I added all the data samples that are used by the frontend application to the readme file.
